//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomidoros.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Pomidoros.Resources.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        internal static string UAPhonePlaceHolder {
            get {
                return ResourceManager.GetString("UAPhonePlaceHolder", resourceCulture);
            }
        }
        
        internal static string PasswordPlaceHolder {
            get {
                return ResourceManager.GetString("PasswordPlaceHolder", resourceCulture);
            }
        }
        
        internal static string EnterBtn {
            get {
                return ResourceManager.GetString("EnterBtn", resourceCulture);
            }
        }
        
        internal static string ForgotPassBtn {
            get {
                return ResourceManager.GetString("ForgotPassBtn", resourceCulture);
            }
        }
        
        internal static string ReceiveNewPassTitle {
            get {
                return ResourceManager.GetString("ReceiveNewPassTitle", resourceCulture);
            }
        }
        
        internal static string EnterNewPhoneLbl {
            get {
                return ResourceManager.GetString("EnterNewPhoneLbl", resourceCulture);
            }
        }
        
        internal static string EnterReceivedSmsCodeLbl {
            get {
                return ResourceManager.GetString("EnterReceivedSmsCodeLbl", resourceCulture);
            }
        }
        
        internal static string ContinueBtn {
            get {
                return ResourceManager.GetString("ContinueBtn", resourceCulture);
            }
        }
    }
}
